import { DropdownOption } from "..";

export const educationOptions: DropdownOption[] = [
	{
		key: "elementary",
		label: "國小",
	},
	{
		key: "junior",
		label: "國中",
	},
	{
		key: "senior",
		label: "高中",
	},
	{
		key: "vocational",
		label: "高職",
	},
	{
		key: "university",
		label: "大學",
	},
	{
		key: "graduate",
		label: "研究所",
	},
];

export const gradeOptions: DropdownOption[] = [
	{
		key: "level_1",
		label: "一年級",
	},
	{
		key: "level_2",
		label: "二年級",
	},
	{
		key: "level_3",
		label: "三年級",
	},
	{
		key: "level_4",
		label: "四年級",
	},
	{
		key: "level_5",
		label: "五年級",
	},
	{
		key: "level_6",
		label: "六年級",
	},
	{
		key: "level_7",
		label: "七年級",
	},
	{
		key: "level_8",
		label: "八年級",
	},
	{
		key: "level_9",
		label: "九年級",
	},
];

export const schoolOptions: DropdownOption[] = [
	{ label: "國立政治大學", key: "nccu" },
	{ label: "國立清華大學", key: "nthu" },
	{ label: "國立臺灣大學", key: "ntu" },
	{ label: "國立臺灣師範大學", key: "ntnu" },
	{ label: "國立成功大學", key: "ncku" },
	{ label: "國立中興大學", key: "nchu" },
	{ label: "國立交通大學", key: "nctu" },
	{ label: "國立中央大學", key: "ncu" },
	{ label: "國立中山大學", key: "nsysu" },
	{ label: "國立臺灣海洋大學", key: "ntou" },
	{ label: "國立中正大學", key: "ccu" },
	{ label: "國立高雄師範大學", key: "nknu" },
	{ label: "國立彰化師範大學", key: "ncue" },
	{ label: "國立陽明大學", key: "ym" },
	{ label: "國立臺北大學", key: "ntpu" },
	{ label: "國立嘉義大學", key: "ncyu" },
	{ label: "國立高雄大學", key: "nuk" },
	{ label: "國立東華大學", key: "ndhu" },
	{ label: "國立暨南國際大學", key: "ncnu" },
	{ label: "國立臺北藝術大學", key: "tnua" },
	{ label: "國立臺灣藝術大學", key: "ntua" },
	{ label: "國立臺東大學", key: "nttu" },
	{ label: "國立宜蘭大學", key: "niu" },
	{ label: "國立聯合大學", key: "nuu" },
	{ label: "國立臺南藝術大學", key: "tnnua" },
	{ label: "國立臺南大學", key: "nutn" },
	{ label: "國立臺北教育大學", key: "ntue" },
	{ label: "國立臺中教育大學", key: "ntcu" },
	{ label: "國立體育大學", key: "ntsu" },
	{ label: "國立金門大學", key: "nqu" },
	{ label: "國立臺灣體育運動大學", key: "ntupes" },
	{ label: "國立屏東大學", key: "nptu" },
	{ label: "國立臺北市立大學", key: "utaipei" },
	{ label: "國立臺灣科技大學", key: "ntust" },
	{ label: "國立雲林科技大學", key: "yuntech" },
	{ label: "國立屏東科技大學", key: "npust" },
	{ label: "國立臺北科技大學", key: "NTUT" },
	{ label: "國立虎尾科技大學", key: "nfu" },
	{ label: "國立澎湖科技大學", key: "NPU" },
	{ label: "國立勤益科技大學", key: "ncut" },
	{ label: "國立臺北護理健康大學", key: "ntunhs" },
	{ label: "國立高雄餐旅大學", key: "nkuht" },
	{ label: "國立臺中科技大學", key: "nutc" },
	{ label: "國立臺北商業大學", key: "NTUB" },
	{ label: "國立高雄科技大學", key: "nkust" },
	{ label: "國立臺灣戲曲學院", key: "TCPA" },
	{ label: "國立臺南護理專科學校", key: "NTIN" },
	{ label: "國立臺東專科學校", key: "NTC" },
	{ label: "國立空中大學", key: "nou" },
	{ label: "國立高雄市立空中大學", key: "ouk" },
	{ label: "私立東海大學", key: "thu" },
	{ label: "私立輔仁大學", key: "fju" },
	{ label: "私立東吳大學", key: "scu" },
	{ label: "私立中原大學", key: "cycu" },
	{ label: "私立淡江大學學校財團法人淡江大學", key: "tku" },
	{ label: "私立中國文化大學", key: "pccu" },
	{ label: "私立逢甲大學", key: "fcu" },
	{ label: "私立靜宜大學", key: "pu" },
	{ label: "私立長庚大學", key: "cgu" },
	{ label: "私立元智大學", key: "yzu" },
	{ label: "私立中華大學學校財團法人中華大學", key: "chu" },
	{ label: "私立大葉大學", key: "dyu" },
	{ label: "私立華梵大學", key: "hfu" },
	{ label: "私立義守大學", key: "isu" },
	{ label: "私立世新大學", key: "shu" },
	{ label: "私立銘傳大學", key: "mcu" },
	{ label: "私立實踐大學", key: "usc" },
	{ label: "私立高雄醫學大學", key: "kmu" },
	{ label: "私立南華大學", key: "nhu" },
	{ label: "私立真理大學", key: "au" },
	{ label: "私立大同大學", key: "ttu" },
	{ label: "私立慈濟學校財團法人慈濟大學", key: "tcu" },
	{ label: "私立臺北醫學大學", key: "tmu" },
	{ label: "私立中山醫學大學", key: "csmu" },
	{ label: "私立長榮大學", key: "cjcu" },
	{ label: "私立中國醫藥大學", key: "cmu" },
	{ label: "私立玄奘大學", key: "hcu" },
	{ label: "私立亞洲大學", key: "asia" },
	{ label: "私立開南大學", key: "knu" },
	{ label: "私立佛光大學", key: "fgu" },
	{ label: "私立明道學校財團法人明道大學", key: "mdu" },
	{ label: "私立台灣首府學校財團法人台灣首府大學", key: "tsu" },
	{ label: "私立康寧學校財團法人康寧大學", key: "ukn" },
	{ label: "私立中信金融管理學院", key: "ctbc" },
	{ label: "私立稻江科技暨管理學院", key: "toko" },
	{ label: "私立馬偕學校財團法人馬偕醫學院", key: "mmc" },
	{ label: "私立法鼓學校財團法人法鼓文理學院", key: "dila" },
	{ label: "私立朝陽科技大學", key: "cyut" },
	{ label: "私立南臺學校財團法人南臺科技大學", key: "stust" },
	{ label: "私立崑山科技大學", key: "ksu" },
	{ label: "私立嘉藥學校財團法人嘉南藥理大學", key: "cnu" },
	{ label: "私立樹德科技大學", key: "stu" },
	{ label: "私立龍華科技大學", key: "lhu" },
	{ label: "私立輔英科技大學", key: "fy" },
	{ label: "私立明新學校財團法人明新科技大學", key: "must" },
	{ label: "私立弘光科技大學", key: "hk" },
	{ label: "私立健行學校財團法人健行科技大學", key: "UCH" },
	{ label: "私立正修學校財團法人正修科技大學", key: "CSU" },
	{ label: "私立萬能學校財團法人萬能科技大學", key: "vnu" },
	{ label: "私立建國科技大學", key: "ctu" },
	{ label: "私立明志科技大學", key: "mcut" },
	{ label: "私立高苑科技大學", key: "kyu" },
	{ label: "私立大仁科技大學", key: "tajen" },
	{ label: "私立聖約翰科技大學", key: "sju" },
	{ label: "私立嶺東科技大學", key: "ltu" },
	{ label: "私立中國科技大學", key: "cute" },
	{ label: "私立中臺科技大學", key: "ctust" },
	{ label: "私立台南家專學校財團法人台南應用科技大學", key: "tut" },
	{ label: "私立遠東科技大學", key: "FEU" },
	{ label: "私立光宇學校財團法人元培醫事科技大學", key: "YPU" },
	{ label: "私立景文科技大學", key: "JUST" },
	{ label: "私立中華醫事科技大學", key: "hwai" },
	{ label: "私立東南科技大學", key: "tnu" },
	{ label: "私立德明財經科技大學", key: "TAKMING" },
	{ label: "私立南開科技大學", key: "nkut" },
	{ label: "私立中華學校財團法人中華科技大學", key: "cust" },
	{ label: "私立僑光科技大學", key: "ocu" },
	{ label: "私立廣亞學校財團法人育達科技大學", key: "ydu" },
	{ label: "私立美和學校財團法人美和科技大學", key: "meiho" },
	{ label: "私立吳鳳科技大學", key: "wfu" },
	{ label: "私立環球學校財團法人環球科技大學", key: "TWU" },
	{ label: "私立中州學校財團法人中州科技大學", key: "CCUT" },
	{ label: "私立修平學校財團法人修平科技大學", key: "hust" },
	{ label: "私立長庚學校財團法人長庚科技大學", key: "cgust" },
	{ label: "私立城市學校財團法人臺北城市科技大學", key: "tpcu" },
	{ label: "私立大華學校財團法人敏實科技大學", key: "MITUST" },
	{ label: "私立醒吾學校財團法人醒吾科技大學", key: "HWU" },
	{ label: "私立文藻學校財團法人文藻外語大學", key: "wzu" },
	{ label: "私立華夏學校財團法人華夏科技大學", key: "hwh" },
	{ label: "私立慈濟學校財團法人慈濟科技大學", key: "tcust" },
	{ label: "私立致理學校財團法人致理科技大學", key: "CHIHLEE" },
	{ label: "私立宏國學校財團法人宏國德霖科技大學", key: "hdut" },
	{ label: "私立東方學校財團法人東方設計大學", key: "tf" },
	{ label: "私立崇右學校財團法人崇右影藝科技大學", key: "cufa" },
	{ label: "私立台北海洋學校財團法人台北海洋科技大學", key: "tumt" },
	{ label: "私立大漢技術學院", key: "dahan" },
	{ label: "私立和春技術學院", key: "fotech" },
	{ label: "私立亞東技術學院", key: "oit" },
	{ label: "私立南亞科技學校財團法人南亞技術學院", key: "nanya" },
	{ label: "私立蘭陽技術學院", key: "FIT" },
	{ label: "私立黎明技術學院", key: "LIT" },
	{ label: "私立經國管理暨健康學院", key: "CKU" },
	{ label: "私立大同技術學院", key: "ttc" },
	{ label: "私立臺灣觀光學院", key: "cit" },
	{ label: "私立馬偕學校財團法人馬偕醫護管理專科學校", key: "mkc" },
	{ label: "私立仁德醫護管理專科學校", key: "jente" },
	{ label: "私立樹人醫護管理專科學校", key: "SZMC" },
	{ label: "私立慈惠醫護管理專科學校", key: "TZUHUI" },
	{ label: "私立耕莘健康管理專科學校", key: "ctcn" },
	{ label: "私立敏惠醫護管理專科學校", key: "MHCHCM" },
	{ label: "私立育英醫護管理專科學校", key: "YUHING" },
	{ label: "私立聖母醫護管理專科學校", key: "SMC" },
	{ label: "私立新生醫護管理專科學校", key: "HSC" },
	{ label: "私立崇仁醫護管理專科學校", key: "CJC" },
	{ label: "私立學校財團法人中華浸信會基督教台灣浸會神學院", key: "tbts" },
	{ label: "私立臺北基督學院", key: "cct" },
	{ label: "私立財團法人一貫道天皇基金會一貫道天皇學院", key: "iktc" },
	{ label: "私立台神學校財團法人台灣神學研究學院", key: "tgst" },
	{ label: "私立一貫道崇德學院", key: "iktcds" },
	{ label: "私立台灣基督長老教會南神神學院", key: "ttcs" },
];

export const majoringOptions: DropdownOption[] = [
	{ key: "math", label: "數學系" },
	{ key: "math", label: "數學系" },
	{ key: "math", label: "數學系" },
	{ key: "math", label: "數學系" },
	{ key: "math", label: "數學系" },
	{ key: "math", label: "數學系" },
	{ key: "math", label: "數學系" },
	{ key: "math", label: "數學系" },
	{ key: "math", label: "數學系" },
	{ key: "math", label: "數學系" },
	{ key: "math", label: "數學系" },
	{ key: "math", label: "數學系" },
	{ key: "math", label: "數學系" },
	{ key: "math", label: "數學系" },
	{ key: "math", label: "數學系" },
	{ key: "math", label: "數學系" },
];
