name: Node.js Package

on:
  push:
    branches:
      - master

jobs:
  # build:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - uses: actions/setup-node@v2
  #       with:
  #         node-version: 12
  #         cache: "yarn"
  #         registry-url: "https://npm.pkg.github.com"
  #         scope: "@methodstudio"
  #     - run: yarn install
  #       env:
  #         NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
  publish-gpr:
    # needs: build
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 12
          registry-url: https://npm.pkg.github.com/
          scope: "@methodstudio"
          cache: "yarn"
      - run: npm config set "@fortawesome:registry" https://npm.fontawesome.com/
      - run: npm config set "//npm.fontawesome.com/:_authToken" ${{ secrets.FONT_AWESOME_TOKEN }}
      - run: yarn install
      - run: npm config set "//npm.pkg.github.com/:_authToken" ${{ secrets.GITHUB_TOKEN }}
      - run: sh ./build.sh
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
